# Generated by Django 5.1.2 on 2024-11-03 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aqtemvaga_brasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('url', models.URLField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='aqtemvaga_regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cidade', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('Salario', models.CharField(max_length=100)),
                ('Requisitos', models.TextField()),
                ('Benificios', models.TextField()),
                ('Descrição', models.TextField()),
                ('Empresa', models.TextField()),
                ('Contato', models.TextField()),
                ('Codigo', models.CharField(max_length=150)),
                ('Data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('Data_atualizacao', models.DateTimeField(auto_now=True)),
                ('Regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aqtemvaga_brasil')),
            ],
        ),
        migrations.CreateModel(
            name='curitiba_regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cidade', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('Salario', models.CharField(max_length=100)),
                ('Requisitos', models.TextField()),
                ('Benificios', models.TextField()),
                ('Descrição', models.TextField()),
                ('Empresa', models.TextField()),
                ('Contato', models.TextField()),
                ('Codigo', models.CharField(max_length=150)),
                ('Data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('Data_atualizacao', models.DateTimeField(auto_now=True)),
                ('Regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aqtemvaga_brasil')),
            ],
        ),
        migrations.CreateModel(
            name='maringa_regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cidade', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('Salario', models.CharField(max_length=100)),
                ('Requisitos', models.TextField()),
                ('Benificios', models.TextField()),
                ('Descrição', models.TextField()),
                ('Empresa', models.TextField()),
                ('Contato', models.TextField()),
                ('Codigo', models.CharField(max_length=150)),
                ('Data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('Data_atualizacao', models.DateTimeField(auto_now=True)),
                ('Regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aqtemvaga_brasil')),
            ],
        ),
    ]
