# Generated by Django 5.0.1 on 2024-11-05 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_empresa', models.CharField(max_length=255)),
                ('descricao_da_empresa', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vaga_oferecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('Cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('Salário', models.CharField(blank=True, max_length=100, null=True)),
                ('Requisitos', models.TextField(blank=True, null=True)),
                ('Benifícios', models.TextField(blank=True, null=True)),
                ('Descrição', models.TextField(blank=True, null=True)),
                ('Empresa', models.TextField(blank=True, null=True)),
                ('Contato', models.TextField(blank=True, null=True)),
                ('Data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('Data_atualizacao', models.DateTimeField(auto_now=True)),
                ('Região', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aqtemvaga_brasil')),
                ('empregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empregador')),
            ],
        ),
    ]
