# Generated by Django 5.0.1 on 2024-11-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empregador_vaga_oferecido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregador',
            name='nome_da_empresa',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
