# Generated by Django 5.0.1 on 2024-11-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_empregador_nome_da_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregador',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
