# Generated by Django 5.0.1 on 2024-11-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_empregador_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqtemvaga_brasil',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aqtemvaga_brasil',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aqtemvaga_brasil',
            name='estado',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aqtemvaga_regiao',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aqtemvaga_brasil',
            name='regiao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
