# Generated by Django 5.0.1 on 2024-11-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vaga_oferecido_bairro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aqtemvaga_brasil',
            old_name='bairro',
            new_name='Bairro',
        ),
        migrations.RenameField(
            model_name='aqtemvaga_brasil',
            old_name='cidade',
            new_name='Cidade',
        ),
        migrations.RenameField(
            model_name='aqtemvaga_brasil',
            old_name='estado',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='vaga_oferecido',
            old_name='empregador',
            new_name='Empregador',
        ),
        migrations.RemoveField(
            model_name='aqtemvaga_brasil',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='vaga_oferecido',
            name='Região',
        ),
        migrations.RemoveField(
            model_name='vaga_oferecido',
            name='bairro',
        ),
        migrations.AddField(
            model_name='vaga_oferecido',
            name='Estado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vaga_oferecido',
            name='Bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
