# Generated by Django 5.0.1 on 2024-11-06 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_bairro_aqtemvaga_brasil_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga_oferecido',
            name='Estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aqtemvaga_brasil'),
        ),
    ]
