# Generated by Django 5.0.1 on 2024-11-08 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_vaga_oferecido_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aqtemvaga_brasil',
            name='Bairro',
        ),
        migrations.RemoveField(
            model_name='aqtemvaga_brasil',
            name='Cidade',
        ),
        migrations.AlterField(
            model_name='aqtemvaga_brasil',
            name='Estado',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='curriculos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
