# Generated by Django 5.0.1 on 2024-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_curriculo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregador',
            name='primeiro_nome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
