# Generated by Django 5.0.1 on 2024-11-12 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_perfilcandidato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacaoCurriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curriculo')),
                ('visualizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
