# Generated by Django 5.0.1 on 2024-11-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_visualizacaocurriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizacaocurriculo',
            name='visualizacoes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
