# Generated by Django 5.0.1 on 2024-11-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_curriculo_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='salario_pretendido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
