# Generated by Django 5.0.1 on 2024-11-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_testeitem_testeview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testeview',
            name='item_teste',
        ),
        migrations.RemoveField(
            model_name='testeview',
            name='view_test',
        ),
        migrations.DeleteModel(
            name='TesteItem',
        ),
        migrations.DeleteModel(
            name='TesteView',
        ),
    ]
