# Generated by Django 5.0.1 on 2024-11-13 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_testeview_item_teste_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='view_perfil_candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vews', models.DateTimeField(auto_now_add=True)),
                ('curriculo_candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculos_candidato', to=settings.AUTH_USER_MODEL)),
                ('curriculo_visualizar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curriculo')),
                ('visualizador_curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculos_visualizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
