# Generated by Django 5.0.1 on 2024-11-13 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_view_perfil_candidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioCurriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curriculo')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vaga_oferecido')),
            ],
            options={
                'unique_together': {('curriculo', 'vaga')},
            },
        ),
    ]
