# Generated by Django 5.0.1 on 2024-11-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_enviocurriculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='usuario',
            field=models.FileField(upload_to='curriculos/'),
        ),
    ]
