# Generated by Django 5.0.1 on 2024-11-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_curriculo_ativo_alter_curriculo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='ativo',
        ),
    ]
