# Generated by Django 5.0.1 on 2024-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_curriculo_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='deletado_pelo_candidato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='deletado_pelo_empregador',
            field=models.BooleanField(default=False),
        ),
    ]
